name = "JuliaSamples"
uuid = "5e099442-531d-422a-8cbb-2a19df64ba17"
authors = ["Sergei Romanenko <sergei.romanenko@supercompilers.ru>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
StaticNumbers = "c5e4b96a-f99f-5557-8ed2-dc63ef9b5131"
