name = "FwDiff"
uuid = "a0b35062-d9e3-4b2c-ad2c-ba287b134e68"
authors = ["Sergei Romanenko <sergei.romanenko@supercompilers.ru>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
