name = "GenPlayground"
uuid = "0f6ed4f4-68d9-4f1d-9948-e05b3ffed299"
authors = ["Sergei Romanenko <sergei.romanenko@supercompilers.ru>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
